### ISSUE TITLE
[Creator profile] Custom links not saving

### ISSUE THREAD

**Issue by Graphi-a** [voidpet/bugs#155]
**Describe the bug**
Custom profile links that you are able to add once you set your profile to a creator profile do not appear on your profile/do not save.

**To Reproduce**
1. Have a creator profile
2.  Go to "edit profile"
3. Click "add link"
4. add name, subtitle, and url/link
5. save
6. go back to profile
7. the link is not present

**Expected behavior**
I expected my link to stay and appear on my profile. It was present on my profile until a few hours ago. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.74

**Comment by benawad** [comment]
Should be fixed now

**Comment by stupidhats** [comment]
Hello! As of the catching update, custom links are still not saving :(
