### ISSUE TITLE
“Internal error” screen

### ISSUE THREAD

**Issue by Calxbedo** [voidpet/bugs#479]
After the latest update, instead of taking you into the game as usual you are met with a red screen reading “internal error” and a string of letters and numbers.
![504CC52D-5D34-47FE-B279-A97569B9B0A8](https://user-images.githubusercontent.com/104241001/164865964-6ff72e35-eb9e-4171-b1ea-02b80dcc7eac.jpeg)

**Comment by benawad** [comment]
could you refresh and see if its fixed for you, I just pushed an update

**Comment by StarsOne** [comment]
![Screenshot_20220423_151122_com opera gx](https://user-images.githubusercontent.com/40720107/164879254-87d8ae83-5fb8-4163-943d-680ce2dc62e6.jpg)
Still shows this for me

**Comment by benawad** [comment]
@cylanskies could you try again
